### ISSUE TITLE
don't read state of the box and a pop up when changing channels

### ISSUE THREAD

**Issue by Stephan296** [Sholofly/Ziggo_Mediabox_Next#1]
My box gives always the state of pause, also when i change channels with your component.
Also is there an popup when i change channels at my tv, not very beautifull ;-)

**Comment by Sholofly** [comment]
Thanks, I made a change yesterday to resolve the first issue. I have seen the pop-up. I will look into it very soon!

**Comment by Stephan296** [comment]
Stil the same problem, i see constantly the status: paused

**Comment by Sholofly** [comment]
Hi @Stephan296, Can you send me your settings? (Please hide credentials) I can't reproduce it at my end. The pop-up is something I'm not able to fix.

**Comment by Stephan296** [comment]
media_player:

  - platform: ziggo-mediabox-next
    username: !secret ziggo_username
    password: !secret ziggo_password


Copy state:


media_player.3c36e4_eosstb_003686187307 | paused | media_content_type: tvshow source_list: NPO 1 HD,NPO 2 HD,NPO 3 HD,RTL 4 HD,RTL 5 HD,SBS6 HD,RTL 7 HD,Veronica HD / Disney XD,Net5 HD,RTL 8 HD,FOX HD,RTL Z HD,Ziggo TV HD,Ziggo Sport HD,Comedy Central HD,Spike HD,Discovery HD,National Geographic Channel HD,SBS9 HD,Eurosport 1 HD,TLC HD,BBC First HD,MTV HD,24Kitchen HD,XITE HD,Viceland HD,Disney Channel HD,HISTORY HD,Nickelodeon HD,ONS,één HD,Canvas HD,Ketnet,ARD HD,ZDF HD,WDR,NDR,RTL,Sat. 1,BBC One HD,BBC Two HD,BBC Three / CBBC,BBC Four / Cbeebies,BBC Entertainment,TV5 Monde,ARTE,TVE,Mediaset Italia,RTV-7,TRT Türk,2M,Film1 Premiere HD,Film1 Action HD,Film1 Family HD,Film1 Drama HD,RTL Crime HD,CI,ID HD,Comedy Central Extra,Shorts TV,E! HD,NPO 1 Extra,OUTTV HD,CBS Reality,Fashion TV HD,MyZen HD,Horse & Country TV  HD,RTL Lounge HD,Discovery Science HD,Discovery World,National Geographic WILD,Love Nature HD,Animal Planet HD,NPO 2 Extra,Family7,Nicktoons,Nick Music,Pebble TV,Nick Jr.,Cartoon Network HD,Boomerang,Baby TV,NPO Zapp Extra,RTL Telekids HD,Ziggo Sport Select,Ziggo Sport Voetbal,Ziggo Sport Golf,Ziggo Sport Racing,Ziggo Sport Docu,Ziggo Sport Extra,Eurosport 2 HD,Extreme Sports Channel,FOX Sports 1 HD,FOX Sports 2 HD,FOX Sports 3 HD,FOX Sports 4 HD,FOX Sports 5 HD,FOX Sports 6 HD,NPO Nieuws,NPO Politiek,CNN,BBC World News,Euronews,Aljazeera English,CNBC Europe,CGTN,RT,TV538,MTV Music 24,DanceTrippin,SLAM,MTV Brand New,Stingray LiteTV,VH1 Classic,Stingray Brava,Mezzo,Stingray DJAZZ,TV Oranje,100% NL TV,192TV,MTV Live HD,TV Noord,Omrop Fryslân,TV Drenthe,TV Oost,TV Gelderland,Omroep Flevoland,NH,RTV Utrecht,TV West,TV Rijnmond,Omroep Zeeland,Omroep Brabant,L1 TV,AT5,STAR Plus,STAR Gold,Zee TV,Zee Cinema,Zing,SET Asia,Show TV,Euro D,Eurostar,Habertürk,TV 8,TRT Çocuk,ATV Avrupa,TRT Müzik,Al Arabiya,MBC,TVM Europe,Aljazeera,Secret Circle,Penthouse HD1,Evil Angel,PassieXXX,DUSK,MvH Hard,X-MO,Zender van de Maand,Testbeeld friendly_name: 3C36E4-EOSSTB-003686187307 icon: mdi:television-classic supported_features: 22960
-- | -- | --

**Comment by Sholofly** [comment]
Hi,

Did you update te source and reboot? I can't reproduce your issue... It's
either playing or off at my side...

Op za 14 sep. 2019 om 23:26 schreef Stephan296 <notifications@github.com>:

**Comment by Sholofly** [comment]
@Stephan296 Please update the component. I think the problem is solved.

**Comment by Stephan296** [comment]
Problem solved indeed, can you also create a state to show the channel?

**Comment by Sholofly** [comment]
I'll dive into that. Please submit a feature request!
