### ISSUE TITLE
Dont see a device

### ISSUE THREAD

**Issue by joostvanmourik** [Sholofly/Ziggo_Mediabox_Next#3]
Hi,

I was using the first version of this project and then saw a device, but know with this version everything seems to be fine but no device media_player.ziggo

What can i do to troubleshoot

**Comment by timon71** [comment]
Probably under another name? In my case it shows up as media_player.3c36e4_eosstb_003773156306.

EOS STB is the product name of the Ziggo Mediabox Next. and the numbers are probably a part of mac address and serialnumber.

**Comment by joostvanmourik** [comment]
Actualy found the device. Thanx
